### ISSUE TITLE
crash: AttributeError: 'module' object has no attribute 'NC_RESIZEN'

### ISSUE THREAD

**Issue by ntfshard** [fifengine/fifengine-editor#23]
Editor starts and crashes after a few seconds. (I didn't install python module; just sources PYTHONPATH)

Python 2.7.9; Opensuse 42.1 x64;
[crashlog.txt](https://github.com/fifengine/fifengine-editor/files/309848/crashlog.txt)

**Comment by prock-fife** [comment]
It seems this bug was introduced here:  https://github.com/fifengine/fifengine/commit/2e9a77fdb49f5619022a310afdb396d7a5e3ea1b

I'm assuming the attribute you want to use is NC_RESIZEWE.

**Comment by ntfshard** [comment]
I'm not sure about '_want to use is NC_RESIZEWE_' =)
I didn't change this code (I just run it)
BTW it looks like this place contains another symbols

Thank you for reply

**Comment by milandamen** [comment]
I can confirm this bug exists. It happens when you mouse over a panel (Layertool, Cellview, Object selector, Object editor etc). Basically the application becomes unusable. The property depends on where you touch a panel, so it can be `NC_RESIZEW`, `NC_RESIZEE`, `NC_RESIZEN`, `NC_RESIZES`

(Running Kubuntu 16.04)

**Comment by LinuxDonald** [comment]
Should be fixed with: https://github.com/fifengine/fifengine-editor/pull/25
